name: CI

on:
  push:
    branches: []

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Verilog Compiler
      uses: jge162/verilog_compiler@1.0.0

    - run: |
        sudo apt-get update
        sudo apt-get install iverilog

    - run: |
        export CDIR=$(pwd)
        echo $(CDIR)
