name: Verible Verilog Lint
on:
  push:
    branches: []

jobs:
  Verible Verilog Lint:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Run Verible action
        uses: chipsalliance/verible-linter-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: verible-linter
          path: verible-linter

      - name: Fail if Simulation Contains Fails
        shell: bash
        run: |
          cat verible-linter
          [[ -s verible-linter ]] && exit 1 || exit 0
