name: Verible linter example

on:
  push:
    branches: [ ]
    
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: chipsalliance/verible-linter-action@main
      with:
        extensions: |
          .sv
          .v
          .vh
          .svh
        github_token: ${{ secrets.GITHUB_TOKEN }}
