name: 'TerosHDL Documenter Action'
autor: Carlos Alberto Ruiz Naranjo, Ismael Pérez Rojo
description: 'Automatically create the documentation for your VHDL/Verilog/SV code. It extracts the comment from the code.'

inputs:
  args:
    description: |
      Options:
        -i, --input [path]        Directory with the HDL files, HDL, file, path of the YML (with EDAM format) file for documenter or CSV. Check the documentation for more information (default: "/home/carlos/workspace/srsLTE_FPGA/lib/src/phy/ue/fpga_ue/common/doc/doc.srs")
        --recursive               If --input is a directory it will search the HDL files in that directory and subdirectories.
        -o, --out [type]          Documentation format: markdown, html (default: "markdown")
        --dep                     Include dependency graph in the documentation.
        --fsm                     Include finite state machines in the documentation.
        -s, --signals <type>      Include signals/regs/wires in the documentation: none,all,only_commented (default: "all")
        -c, --constants <type>    Include constants/types in the documentation: none,all,only_commented (default: "all")
        -p, --process <type>      Include process/always in the documentation: none,all,only_commented (default: "all")
        -f, --functions <type>    Include functions in the documentation: none,all,only_commented (default: "all")
        --symbol_verilog, <type>  Special character to parse comments into documentation (default: "")
        --symbol_vhdl <type>      Special character to parse comments into documentation (default: "")
        --pypath, <type>          Explicit python path (default: "")
        --outpath, <type>         Explicit outputh documentation path (default: "")
        --self_contained          Documentation generated in a single file for html output

    default: "-i ./ --recursive --dep --out html --fsm -s all -c all -p all -f all --outpath teroshdl_doc"
    required: false

runs:
  using: "composite"
  steps: 
    - run: sudo pip3 install --quiet vunit_hdl
      shell: bash
      
    - run: sudo npm install --silent -g git://github.com/TerosTechnology/colibri.git#master
      shell: bash

    - run: teroshdl-hdl-documenter ${{ inputs.args }}
      shell: bash

branding:
  icon: cpu
  color: red
