name: Vivado CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: make CI

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        path: ___CI_REPORT
      
